version: '3.8'

services:
  web:
    build: ../
    ports:
      - "8000:80"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/appdb
      - SECRET_KEY=ABCDE
      - TOKEN_EXPIRY_TIME=2000
      - API_VERSION=/api/v1
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=appdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: